language: go

os:
  - linux
  - osx

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

install:
  - make install-dependencies
  - make install-tools
  - make install

script:
  - make lint
  - make test-with-coverage
  - gover
  - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then goveralls -coverprofile=gover.coverprofile -service=travis-ci; fi
